package com.canopobd.ui.navigation

sealed class NavRoute(val route: String) {
    data object Dashboard : NavRoute("dashboard")
    data object Settings : NavRoute("settings")
    data object Dtc : NavRoute("dtc")
    data object DataLog : NavRoute("data_log")
    data object Pids : NavRoute("pids")
    data object RemoteServer : NavRoute("remote_server")
    data object TripComputer : NavRoute("trip_computer")
    data object Customization : NavRoute("customization")
    data object Hud : NavRoute("hud")
    data object TrendGraph : NavRoute("trend_graph")
    data object Readiness : NavRoute("readiness")
    data object Diagnostics : NavRoute("diagnostics")
    data object Alerts : NavRoute("alerts")
    data object DataAnalysis : NavRoute("data_analysis")
    data object FuelEconomy : NavRoute("fuel_economy")
    data object Maintenance : NavRoute("maintenance")
    data object PerformanceTest : NavRoute("performance_test")
    data object TripHistory : NavRoute("trip_history")
    data object PowerCalculator : NavRoute("power_calculator")
    data object DriveScore : NavRoute("drive_score")
    data object ShiftLight : NavRoute("shift_light")
    data object TurboMonitor : NavRoute("turbo_monitor")
    data object TimingChainMonitor : NavRoute("timing_chain_monitor")
    data object CarProfile : NavRoute("car_profile")
    data object TurboCooldown : NavRoute("turbo_cooldown")
    data object DevicePicker : NavRoute("device_picker")
}
